const foo = () => {
    throw Error('foo에서 발생한 에러'); // ④
  };
  
  const bar = () => {
    foo(); // ③
  };
  
  const baz = () => {
    bar(); // ②
  };
  
  try {
    baz(); // ①
  } catch (err) {
    console.error(err);
  }
  